FROM eclipse-temurin:19.0.2_7-jdk-alpine as gradle
RUN apk add --no-cache gradle

FROM gradle as builder
USER root
ENV APP_HOME=/builder
WORKDIR $APP_HOME
COPY . $APP_HOME
RUN gradle test --stacktrace --no-daemon --no-build-cache --parallel
