FROM eclipse-temurin:19.0.2_7-jdk-alpine as GRADLE
USER root
COPY *.gradle gradle.* gradlew /src/
COPY gradle /src/gradle
WORKDIR /src
RUN ["./gradlew", "--version"]

FROM GRADLE as BUILDER
COPY . .
RUN ["./gradlew", "clean"]

FROM BUILDER
RUN [ "./gradlew", "test", "--stacktrace", "--no-daemon", "--parallel"]