FROM eclipse-temurin:20.0.1_9-jdk-alpine as gradle
RUN apk add --no-cache gradle

FROM gradle as builder
USER root
ENV APP_HOME=/builder
WORKDIR $APP_HOME
COPY . $APP_HOME
RUN gradle build --stacktrace --no-daemon